name: fluttemp
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  dio: ^5.3.2
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^4.2.1
  flutter_bloc: ^8.1.4
  awesome_snackbar_content: ^0.1.3
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  contacts_service: ^0.6.3
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.3


flutter:
  uses-material-design: true
  assets:
    - assets/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  

